# Generated by Django 3.2.7 on 2021-09-29 03:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=1000)),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 29, 8, 51, 52, 608911))),
            ],
        ),
    ]
