# Generated by Django 3.2.7 on 2021-09-29 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='course',
        ),
    ]
