# Generated by Django 3.2.7 on 2021-10-03 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='course',
        ),
    ]
