# Generated by Django 3.2.7 on 2021-10-03 03:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0004_delete_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=1000)),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 3, 8, 33, 29, 204498))),
                ('duration', models.CharField(max_length=50)),
                ('start', models.DateField()),
                ('payment', models.CharField(max_length=100)),
                ('via', models.CharField(max_length=25)),
            ],
        ),
    ]
