# Generated by Django 3.2.7 on 2021-10-03 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='join',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('interested', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=12)),
            ],
        ),
        migrations.DeleteModel(
            name='course',
        ),
    ]
