# Generated by Django 3.2.7 on 2021-10-03 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 3, 12, 21, 15, 881439)),
        ),
    ]
