# Generated by Django 3.2.7 on 2021-09-28 02:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=100000)),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 28, 8, 0, 47, 174512))),
            ],
        ),
    ]
