# Generated by Django 3.2.7 on 2021-10-03 03:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_alter_blogp_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogp',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 3, 9, 28, 21, 44664)),
        ),
    ]
